services:
  k3s-server:
    hostname: k3s-server
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    privileged: true
    volumes:
      - ./.kubeconfig:/kubeconfig
      - .k3s-server:/var/lib/rancher/k3s
    command: server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "6443:6443"
    environment:
      - K3S_TOKEN=2c538a14fa510963f2ec22d51c3edd156a3b5cc4
      - K3S_KUBECONFIG_OUTPUT=/kubeconfig/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    healthcheck:
      test: ["CMD", "kubectl", "get", "nodes"]
      interval: 10s
      timeout: 5s
      retries: 3

  k3s-agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://k3s-server:6443
    - K3S_TOKEN=2c538a14fa510963f2ec22d51c3edd156a3b5cc4
    volumes:
    - k3s-agent:/var/lib/rancher/k3s

  api:
    image: api
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./.kubeconfig:/kubeconfig
    depends_on:
      - k3s-server
    environment:
      KUBECONFIG: /kubeconfig/kubeconfig.yaml
      CLUSTER_URL: https://k3s-server:6443

volumes:
  k3s-server: {}
  k3s-agent: {}