apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-lab.fullname" . }}-app
  labels:
    app: kube-lab
    owner: k8s
    {{- include "kube-lab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kube-lab
      {{- include "kube-lab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: "{{ .Values.linkerd.inject }}"
      labels:
        app: kube-lab
        owner: k8s
        {{- include "kube-lab.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kube-lab-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: 8000
          env:
            - name: KUBECONFIG_BASE64
              valueFrom:
                secretKeyRef:
                  name: {{ include "kube-lab.kubeconfigSecretName" . }}
                  key: kubeconfig
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml | nindent 8 }}