apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-lab.authTokenSecretName" . }}
  labels:
    app: kube-lab
    owner: k8s
    {{- include "kube-lab.labels" . | nindent 4 }}
type: Opaque
data:
  authToken: {{ .Values.authToken | b64enc }}