apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-lab.kubeconfigSecretName" . }}
  labels:
    app: kube-lab
    owner: k8s
    {{- include "kube-lab.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.kubeconfigBase64 }}