
image:
  repository: johnnytardin/kube-lab
  tag: latest

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

replicas: 2

nodeSelector:
  kubernetes.io/os: linux
  workload: general

service:
    ports:
    - port: 8000
      targetPort: 8000
    type: ClusterIP

ingress:
  enabled: true
  ingressClassName: web
  host: kube-lab.local

linkerd:
  inject: true