name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install --no-cache-dir poetry
            poetry config virtualenvs.create false && poetry install --no-dev

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        run: flake8 app/

  docker_lint:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:v2.12.1-beta-debian
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        run: hadolint Dockerfile

  build_docker:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: johnnytardin/kube-lab:latest

  security:
    runs-on: ubuntu-latest
    needs: [ build, build_docker ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: johnnytardin/kube-lab:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
